hunter_add_package(Arkitekto)
find_package(Arkitekto CONFIG REQUIRED)
akt_hunter_get_install_root(hunter_install_root)
find_package(Threads REQUIRED)
if(BUILD_TEST)
    hunter_add_package(GTest)
    find_package(GTest CONFIG REQUIRED)
endif()
if(WIN32)
    set(H_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
    unset(CMAKE_MODULE_PATH)
    find_package(OpenSSL REQUIRED)
    set(CMAKE_MODULE_PATH ${H_CMAKE_MODULE_PATH})
else()
    hunter_add_package(OpenSSL)
    find_package(OpenSSL REQUIRED)
endif()
hunter_add_package(Boost COMPONENTS locale)
find_package(Boost COMPONENTS locale CONFIG REQUIRED)
if(ENV{LIBS})
    set(ENV{LIBS} "$ENV{LIBS};-lpthread")
else()
    set(ENV{LIBS} "-lpthread")
endif()
message(STATUS "ENV{LIBS} = $ENV{LIBS}")
hunter_add_package(sqlpp17)
find_package(sqlpp17 CONFIG REQUIRED)
hunter_add_package(pixiu)
find_package(pixiu CONFIG REQUIRED)
hunter_add_package(bcrypt)
find_package(bcrypt CONFIG REQUIRED)
